"""Scoped video submission and polling; callers own video delivery."""

import asyncio
import hashlib
import json
import uuid
from contextlib import asynccontextmanager
from dataclasses import asdict

from ..grok_oauth.errors import (
    GrokOAuthError,
    InvalidRequest,
    PermissionDenied,
    ServiceClosed,
)
from ..grok_oauth.videos import VideoRequest
from .compat import FunctionTool, Image, Reply, TextPart, ToolSet, selected_chat_provider
from .provider import is_runtime_provider
from .tool_scope import VIDEO_TOOL_NAMES, consume_tool_call


class GrokVideoFunctionTool(FunctionTool):
    """Keep the host registration owned by this plugin module."""


class VideoToolService:
    def __init__(self, context, runtime, image_tools):
        self.context = context
        self.runtime = runtime
        self.image_tools = image_tools
        self.closed = False
        self._foreground = set()

    async def resolve_provider(self, event, *, from_tool=False, calling_provider=None):
        if self.closed or self.runtime.closed:
            raise ServiceClosed()
        if not self.runtime.config.get("videos_enabled", True) or not self.runtime.config.get(
            "tools_enabled", True
        ):
            raise PermissionDenied("Video tools are disabled")
        selected = self.runtime.config.get("tools_provider_id")
        if selected:
            provider = self.context.get_provider_by_id(selected)
        elif from_tool:
            provider = calling_provider
        else:
            provider = await selected_chat_provider(self.context, event)
        if not is_runtime_provider(provider, self.runtime):
            raise PermissionDenied("Select a Grok video provider in plugin settings")
        return provider

    async def scope(self, event):
        return await self.image_tools.scope(event)

    def build_tools(self):
        prompt = {"type": "string", "minLength": 1, "description": "Describe the video or edit."}
        reference = {
            "type": "string",
            "minLength": 1,
            "description": "Current-conversation asset ID. Never pass a path, URL or base64 data.",
        }
        specs = [
            (
                VIDEO_TOOL_NAMES[0],
                "Animate an existing current-conversation image with Grok. Returns a job ID; the caller owns polling, downloading and delivery. Repeating the same request in this message reuses the job.",
                {
                    "prompt": prompt,
                    "reference_asset_id": reference,
                    "duration": {"type": "integer", "enum": [6, 10]},
                },
                ["prompt", "reference_asset_id"],
                self._tool_generate,
            ),
            (
                VIDEO_TOOL_NAMES[1],
                "Edit a video previously generated by this plugin in the current conversation. Input duration must not exceed 8.7 seconds. Returns a job ID; the caller owns polling, downloading and delivery.",
                {"prompt": prompt, "reference_asset_id": reference},
                ["prompt", "reference_asset_id"],
                self._tool_edit,
            ),
            (
                VIDEO_TOOL_NAMES[2],
                "Query a current-conversation Grok video job. Querying does not regenerate or resend a video. Use its asset ID as an edit reference once done.",
                {"job_id": {"type": "string", "minLength": 1}},
                ["job_id"],
                self._tool_status,
            ),
        ]
        return [
            GrokVideoFunctionTool(
                name=name,
                description=description
                + " Available to Grok OAuth models by default; other models require explicit administrator configuration.",
                parameters={
                    "type": "object",
                    "properties": properties,
                    "required": required,
                    "additionalProperties": False,
                },
                handler=handler,
            )
            for name, description, properties, required, handler in specs
        ]

    async def prepare(self, event, req):
        if not req.func_tool:
            return
        tools = list(req.func_tool.tools)
        if not any(tool.name in VIDEO_TOOL_NAMES for tool in tools):
            return
        try:
            await self.resolve_provider(event)
        except GrokOAuthError:
            req.func_tool = ToolSet([tool for tool in tools if tool.name not in VIDEO_TOOL_NAMES])
            return
        if not any(tool.name == VIDEO_TOOL_NAMES[0] and tool.active for tool in tools):
            return
        try:
            scope = await self.scope(event)
            cache = event.get_extra("grok_imported_image_assets")
            if (
                isinstance(cache, dict)
                and cache.get("scope") == scope
                and isinstance(cache.get("asset_ids"), list)
                and all(isinstance(asset_id, str) and asset_id for asset_id in cache["asset_ids"])
            ):
                assets = list(cache["asset_ids"])
            else:
                components = list(event.message_obj.message or [])
                images = []
                for component in components:
                    if isinstance(component, Image):
                        images.append(component)
                    elif isinstance(component, Reply):
                        images.extend(
                            part for part in component.chain or [] if isinstance(part, Image)
                        )
                if len(images) > 5:
                    raise InvalidRequest("At most five message images can be imported")
                assets = [
                    await self.runtime.assets.import_reference(
                        image.url or image.file or image.path,
                        scope=scope,
                        allowed_roots=self.runtime.allowed_roots,
                    )
                    for image in images
                ]
            if assets:
                req.extra_user_content_parts.append(
                    TextPart(
                        text="当前会话可用于生成视频的图片资产，按附件顺序：" + json.dumps(assets)
                    )
                )
        except GrokOAuthError as error:
            req.extra_user_content_parts.append(
                TextPart(text="Grok 视频参考图片无法导入：" + error.code)
            )

    @asynccontextmanager
    async def _operation(self):
        if self.closed:
            raise ServiceClosed()
        task = asyncio.current_task()
        self._foreground.add(task)
        try:
            yield
        finally:
            self._foreground.discard(task)

    async def _tool_generate(self, event, **arguments):
        return await self._run("generate", event, arguments, from_tool=True)

    async def _tool_edit(self, event, **arguments):
        return await self._run("edit", event, arguments, from_tool=True)

    async def _tool_status(self, event, **arguments):
        try:
            if set(arguments) != {"job_id"}:
                raise InvalidRequest()
            provider = consume_tool_call(self.runtime, VIDEO_TOOL_NAMES[2], arguments)
            await self.resolve_provider(event, from_tool=True, calling_provider=provider)
            async with self._operation():
                job = await self.runtime.videos.poll(
                    arguments["job_id"], scope=await self.scope(event), timeout=30
                )
                return self._result(job)
        except GrokOAuthError as error:
            return self._error(error)

    async def generate(self, event, **arguments):
        return await self._run("generate", event, arguments)

    async def edit(self, event, **arguments):
        return await self._run("edit", event, arguments)

    @staticmethod
    def _error(error):
        return json.dumps({"status": "error", **error.summary()}, ensure_ascii=False)

    async def _run(self, action, event, arguments, *, from_tool=False):
        try:
            async with self._operation():
                allowed = {"prompt", "reference_asset_id"} | (
                    {"duration"} if action == "generate" else set()
                )
                if set(arguments) - allowed:
                    raise InvalidRequest("Unknown video tool argument")
                provider = (
                    consume_tool_call(self.runtime, "grok_video_" + action, arguments)
                    if from_tool
                    else None
                )
                await self.resolve_provider(event, from_tool=from_tool, calling_provider=provider)
                scope = await self.scope(event)
                prompt, reference = arguments.get("prompt"), arguments.get("reference_asset_id")
                if (
                    not isinstance(prompt, str)
                    or not prompt.strip()
                    or not isinstance(reference, str)
                    or not reference
                ):
                    raise InvalidRequest("A prompt and scoped reference asset are required")
                duration = arguments.get("duration", 6)
                if type(duration) is not int or duration not in (6, 10):
                    raise InvalidRequest("Video duration must be 6 or 10 seconds")
                request = VideoRequest(
                    prompt=str(prompt),
                    reference_asset_id=reference,
                    action=action,
                    duration=duration,
                    resolution="480p",
                )
                message_id = str(getattr(event.message_obj, "message_id", "") or "")
                if not message_id:
                    message_id = event.get_extra("grok_video_operation_nonce")
                    if not message_id:
                        message_id = uuid.uuid4().hex
                        event.set_extra("grok_video_operation_nonce", message_id)
                key = hashlib.sha256(
                    json.dumps(
                        [asdict(scope), message_id, asdict(request)],
                        sort_keys=True,
                        ensure_ascii=False,
                    ).encode()
                ).hexdigest()
                job = await self.runtime.videos.submit(request, scope=scope, operation_key=key)
                return self._result(job)
        except GrokOAuthError as error:
            return self._error(error)

    @staticmethod
    def _result(job):
        result = job.public()
        result["delivery_owner"] = "caller"
        return json.dumps(result, ensure_ascii=False)

    async def status(self, event, job_id):
        try:
            async with self._operation():
                await self.resolve_provider(event)
                job = await self.runtime.videos.poll(
                    job_id, scope=await self.scope(event), timeout=30
                )
                return self._result(job)
        except GrokOAuthError as error:
            return self._error(error)

    async def close(self):
        self.closed = True
        tasks = set(self._foreground)
        tasks.discard(asyncio.current_task())
        for task in tasks:
            task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
